project_id = "nnvfcvpoldufojsxcfzo"

[functions.login-by-username]
verify_jwt = false

[functions.seed-employees]
verify_jwt = false

[functions.seed-shifts]
verify_jwt = false

[functions.manage-employee]
verify_jwt = false