project_id = "rrjmkqpexcjsqkxenpet"

[functions.login-by-username]
verify_jwt = false

[functions.seed-employees]
verify_jwt = false

[functions.seed-shifts]
verify_jwt = false

[functions.manage-employee]
verify_jwt = false

[functions.seed-salary-test]
verify_jwt = false

[functions.seed-stock-reports]
verify_jwt = false

[functions.seed-salary-entries]
verify_jwt = false

[functions.create-new-accounts]
verify_jwt = false

[functions.manage-june-rates]
verify_jwt = false

[functions.inspect-type-b]
verify_jwt = false

[functions.temp-test-accounts]
verify_jwt = false