-- Seed vegetable ingredients from ingredient-categories.json
-- Categories: leafy_green, herb, root, fruit_veg, mushroom, stem

INSERT INTO public.ingredients (id, name, emoji, unit, category, subcategory) VALUES
-- Leafy greens
('leafy_green_rau_muong', 'Rau muống', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_ngot', 'Rau ngót', '🌿', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_mong_toi', 'Mồng tơi', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_den', 'Rau dền', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_ngot', 'Cải ngọt', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_thia', 'Cải thìa', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_thao', 'Cải thảo', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_bo_xoi', 'Cải bó xôi', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_bap_cai', 'Bắp cải', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_lang', 'Rau lang', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_ma', 'Rau má', '🌿', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_xa_lach', 'Xà lách', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_be_xanh', 'Cải bẹ xanh', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_tia_to', 'Tía tô (lá)', '🌿', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_xoong', 'Cải xoong', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_cai_chip', 'Cải chip', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_la_lot', 'Lá lốt', '🌿', 'cái', 'vegetables', 'leafy-greens'),
('leafy_green_rau_diep', 'Rau diếp', '🥬', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_sam', 'Rau sam', '🌿', 'kg', 'vegetables', 'leafy-greens'),
('leafy_green_rau_day', 'Rau đay', '🌿', 'kg', 'vegetables', 'leafy-greens'),

-- Herbs
('herb_rau_mui', 'Rau mùi', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_thi_la', 'Thì là', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_hanh_la', 'Hành lá', '🧅', 'kg', 'vegetables', 'allium-vegetables'),
('herb_ngo_ri', 'Ngò rí', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_kinh_gioi', 'Kinh giới', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_rau_ram', 'Rau răm', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_hung_que', 'Húng quế', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_hung_cay', 'Húng cây', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_la_que', 'Lá quế', '🍂', 'cái', 'vegetables', 'allium-vegetables'),
('herb_sa', 'Sả', '🌾', 'cái', 'vegetables', 'allium-vegetables'),
('herb_hanh_tay', 'Hành tây', '🧅', 'cái', 'vegetables', 'allium-vegetables'),
('herb_he', 'Hẹ', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_bac_ha', 'Bạc hà', '🌿', 'kg', 'vegetables', 'allium-vegetables'),
('herb_mui_tau', 'Mùi tàu', '🌿', 'kg', 'vegetables', 'allium-vegetables'),

-- Root vegetables
('root_ca_rot', 'Cà rốt', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_khoai_tay', 'Khoai tây', '🥔', 'kg', 'vegetables', 'root-vegetables'),
('root_khoai_lang', 'Khoai lang', '🍠', 'kg', 'vegetables', 'root-vegetables'),
('root_khoai_mo', 'Khoai mỡ', '🍠', 'kg', 'vegetables', 'root-vegetables'),
('root_khoai_mon', 'Khoai môn', '🍠', 'kg', 'vegetables', 'root-vegetables'),
('root_cai_cai_trang', 'Củ cải trắng', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_cai_cai_do', 'Củ cải đỏ', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_su_hao', 'Su hào', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_sen', 'Củ sen', '🌰', 'kg', 'vegetables', 'root-vegetables'),
('root_gung', 'Gừng', '🫚', 'kg', 'vegetables', 'root-vegetables'),
('root_nghe', 'Nghệ', '🫚', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_san', 'Củ sắn', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_den', 'Củ dền', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_kieu', 'Củ kiệu', '🧅', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_nom', 'Củ nén', '🧄', 'kg', 'vegetables', 'root-vegetables'),
('root_cu_dau', 'Củ đậu', '🥕', 'kg', 'vegetables', 'root-vegetables'),
('root_khoai_mai', 'Khoai mài', '🍠', 'kg', 'vegetables', 'root-vegetables'),

-- Fruiting vegetables
('fruit_veg_ca_chua', 'Cà chua', '🍅', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_ca_tim', 'Cà tím', '🍆', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_bau', 'Bầu', '🍈', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_bi_do', 'Bí đỏ', '🎃', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_bi_ngoi', 'Bí ngòi', '🥒', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_muop', 'Mướp', '🥒', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_kho_qua', 'Khổ qua', '🥒', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_dau_bap', 'Đậu bắp', '🫛', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_ot_chuong', 'Ớt chuông', '🫑', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_vec_ngo_bap', 'Ngô/Bắp', '🌽', 'cái', 'vegetables', 'stem-vegetables'),
('fruit_veg_dau_cove', 'Đậu cove', '🫛', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_dau_dua', 'Đậu đũa', '🫛', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_dau_rong', 'Đậu rồng', '🫛', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_dau_non', 'Đậu non', '🫛', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_mang', 'Măng', '🎋', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_mit_non', 'Mít non', '🍈', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_muop_dang', 'Mướp đắng', '🥒', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_dua_leo', 'Dưa leo', '🥒', 'cái', 'vegetables', 'stem-vegetables'),
('fruit_veg_bi_xanh', 'Bí xanh', '🥒', 'kg', 'vegetables', 'stem-vegetables'),
('fruit_veg_ca_pha', 'Cà pháo', '🍆', 'kg', 'vegetables', 'stem-vegetables'),

-- Mushrooms
('mushroom_nam_rom', 'Nấm rơm', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_dong_co', 'Nấm đông cô', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_kim_cham', 'Nấm kim châm', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_dui_ga', 'Nấm đùi gà', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_bao_ngu', 'Nấm bào ngư', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_meo', 'Nấm mèo', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_moi', 'Nấm mối', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_huong', 'Nấm hương', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_linh_chi', 'Nấm linh chi', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_mo', 'Nấm mỡ', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_so', 'Nấm sò', '🍄', 'kg', 'vegetables', 'leafy-greens'),
('mushroom_nam_tuyet', 'Nấm tuyết', '🍄', 'kg', 'vegetables', 'leafy-greens'),

-- Stem vegetables
('stem_can_tay', 'Cần tây', '🌱', 'kg', 'vegetables', 'stem-vegetables'),
('stem_mang_tay', 'Măng tây', '🌱', 'kg', 'vegetables', 'stem-vegetables'),
('stem_bong_cai_xanh', 'Bông cải xanh', '🥦', 'kg', 'vegetables', 'stem-vegetables'),
('stem_bong_cai_trang', 'Bông cải trắng', '🥦', 'kg', 'vegetables', 'stem-vegetables'),
('stem_atiso', 'Atisô', '🌱', 'cái', 'vegetables', 'stem-vegetables'),
('stem_can_nuoc', 'Cần nước', '🌱', 'kg', 'vegetables', 'stem-vegetables'),
('stem_doc_mung', 'Dọc mùng', '🌱', 'kg', 'vegetables', 'stem-vegetables'),
('stem_gia_do', 'Giá đỗ', '🌱', 'kg', 'vegetables', 'stem-vegetables'),
('stem_than_chuoi', 'Thân chuối', '🌱', 'kg', 'vegetables', 'stem-vegetables')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  emoji = EXCLUDED.emoji,
  unit = EXCLUDED.unit,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory;
